// Code generated by hertz generator.

package user

import (
	"context"
	"time"

	user "github.com/click33/sa-token-go/examples/hertz/herz-example/biz/model/user"
	sahertz "github.com/click33/sa-token-go/integrations/hertz"
	"github.com/click33/sa-token-go/stputil"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Login .
// @router /login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	token, err := stputil.Login(req.GetUserId())
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	loginID, err := stputil.GetLoginID(token)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	err = stputil.SetRoles(loginID, []string{"manager"})
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.LoginResp)
	resp.Token = token

	c.JSON(consts.StatusOK, resp)
}

// Public .
// @router /public [GET]
func Public(ctx context.Context, c *app.RequestContext) {

	resp := new(user.MessageResp)
	resp.Message = "public"

	c.JSON(consts.StatusOK, resp)
}

// UserInfo .
// @router /user [GET]
func UserInfo(ctx context.Context, c *app.RequestContext) {

	resp := new(user.UserInfoResp)
	// 优先读取 TokenInterceptor 写入的 token，未接入拦截器时回退到默认 satoken 头
	token := sahertz.GetTokenFromCtx(c)
	if token == "" {
		token = string(c.Request.Header.Get("satoken"))
	}
	loginID, err := stputil.GetLoginID(token)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	roles, _ := stputil.GetRoles(loginID)
	permissions, _ := stputil.GetPermissions(loginID)

	resp.LoginId = loginID
	resp.Roles = roles
	resp.Permissions = permissions

	c.JSON(consts.StatusOK, resp)
}

// Admin .
// @router /admin [GET]
func Admin(ctx context.Context, c *app.RequestContext) {

	resp := new(user.MessageResp)
	resp.Message = "admin"

	c.JSON(consts.StatusOK, resp)
}

// Manager .
// @router /manager [GET]
func Manager(ctx context.Context, c *app.RequestContext) {

	resp := new(user.MessageResp)
	resp.Message = "manager"

	c.JSON(consts.StatusOK, resp)
}

// Sensitive .
// @router /sensitive [GET]
func Sensitive(ctx context.Context, c *app.RequestContext) {

	resp := new(user.SensitiveResp)
	token := sahertz.GetTokenFromCtx(c)
	if token == "" {
		token = string(c.Request.Header.Get("satoken"))
	}
	loginID, err := stputil.GetLoginID(token)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp.Sensitive = stputil.IsDisable(loginID)

	c.JSON(consts.StatusOK, resp)
}

// Disable .
// @router /disable [GET]
func Disable(ctx context.Context, c *app.RequestContext) {
	var err error

	token := sahertz.GetTokenFromCtx(c)
	if token == "" {
		token = string(c.Request.Header.Get("satoken"))
	}
	loginID, err := stputil.GetLoginID(token)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	err = stputil.Disable(loginID, time.Hour)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(user.MessageResp)

	c.JSON(consts.StatusOK, resp)
}
